### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mogikanin** [winnster/DotRas#2]
Hello Jeff,
Just noticed this repo :) Seems like you back to DotRas development. Does it mean it will be revised version of DotRas soon?
Could you disclosure some info about it? Is it will be available for public/commercial use, will it work on Win7+ and any Windows 10 versions, and do you have plans to support periodical updates/synchronize with latest Windows SDKs?

Thanks, 
Maxim.

**Comment by jeff-winn** [comment]
Maxim,

It's currently a rewrite, so "soon" may not be soon enough for what you're after given this is a free time project for me on my own schedule. The old patterns in the previous 1.x version really needed to be fixed before any long term maintenance of the product could be done. It was one of the biggest issues I had with that particular API.

As for the public/commercial use, please refer to the license that is currently checked in [here](https://github.com/winnster/DotRas/blob/master/LICENSE) it will tell you what the license may or may not be used for.

Regarding which operating systems are planned, the new branching strategy should be more accommodating for adapting to changes that Microsoft is making to their operating system, but I do not plan to provide support for older operating systems outside of Microsoft's own end of life as they have made clear [here](https://www.microsoft.com/en-us/windowsforbusiness/end-of-windows-7-support).

Currently I'm planning on setting up:
- Windows 7
- Windows 8
- Windows 10

With the new codebase ensuring that unit testing is a high priority it will be a lot easier to support long term more so than what the previous versions were. There's still quite a bit of work that needs to be done between getting documentation written and writing the code around the APIs.

Hope that helps,
Jeff

**Comment by mogikanin** [comment]
OK, I get you Jeff. Thanks!

**Comment by jeff-winn** [comment]
If there are specific things you need out of the API feel free to submit an issue and I will try to get to them early. However just be aware given the new release strategy Windows 10 will need to be the last thing I add support for.

This project isn’t closed access either, I haven’t had a chance to add the documentation to support contributing but I am not opposed to it.

**Comment by mogikanin** [comment]
OK, here it is a list of features from DotRas 1.x we are using in our VPN app. I guess all of them should be in new version. Somewhere I use class names from DotRas 1.x :)

- [x]  Specify path to phonebook file
- [ ] Read\write\edit phonebook entries
- [ ] Entry edit abilities: `PhoneNumber`, `Options.RemoteDefaultGateway`, `DnsAddress\DnsAddressAlt`, `Options.RegisterIPWithDns`, `Options.UseDnsSuffixForRegistration`. `DnsSuffix`, `Options.RequireChap`, `Options.RequireMSEncryptedPassword`, `Options.RequireMSChap`, `Options.RequireMSChap2`, `Options.UsePreSharedKey`, `UpdateCredentials(RasPreSharedKey key, string value)`, `RedialCount`, `RedialPause`, `VpnStrategy`, `Options.ReconnectIfDropped`. `Options.SecureClientForMSNet`, `Options.SecureFileAndPrint`, `NetworkProtocols.IPv6`
- [x] Get a list of active connections `RasConnection.GetActiveConnections()`
- [x] Get connection status\state for given connection.
- [ ] RasDialer: `InterfaceIndex`. Events: `DialCompleted`, `StateChanged` with ability to catch events not only while a connection is being dialed, but also **catch connection disconnects** - in 1.x there is a separate `RasConnectionWatcher` for this.

**Comment by jeff-winn** [comment]
The RasPhoneBook class is probably one of the larger classes to setup since it is the one that is most dependent on specific versions of Windows. I’ve been contemplating how I can make it easier to interact with (like implementing a unit of work pattern and using an internal change manager with SaveChanges method).

Some of the things you’re asking for have already been implemented: 
- RasConnection.GetActiveConnections that should already exist as RasConnection.EnumerateConnections
- The RasDialer no longer needs the DialCompleted event as that was part of the old Event-based Asynchronous pattern from .NET 2.0. You can now simply use DialAsync and await it. InterfaceIndex hasn’t been added yet, but I suppose I could get all the variant branches setup and finish it.

Regarding the RasDialer getting told about other connection disconnects, the RasConnectionWatcher will likely still remain. There is a lot of heavy complexity on being told by Windows when that happens and I’d rather not break SOLID rules and increase the responsibility of the RasDialer beyond just dialing a connection.

**Comment by mogikanin** [comment]
OK, this makes sense. If you want port RasConnectionWatcher as is, please take care about critical bug (original issue №17567 on codeplex: `ArgumentOutOfRangeException when changing RasConnectionWatcher.Handle`). We workaround it with no using `RasConnectionWatcher.Handle` at all :)

**Comment by jeff-winn** [comment]
If you'd like to create a feature enhancement for this and just put a brief description of how you'd like to monitor the connections (and what case you're trying to use the handle with) that would be super helpful.

Also, would you be willing to test it to make sure it meets your needs?

**Comment by mogikanin** [comment]
The usage is quite simple. We have vpn connection with corresponding handle. Our goal is detect unexpected vpn disconnection and perform specific actions on that event. 

Yes, sure, I'll test it.

**Comment by jeff-winn** [comment]
The connection you're trying to monitor changes in state, is that a connection you've created using the dialer or is it another connection?

Trying to determine if a Disconnected event being added to RasConnection would be viable.

**Comment by mogikanin** [comment]
Both cases, Jeff.

**Comment by jeff-winn** [comment]
You may want to check out the WIN7 branch for the RasDialer class when you get a chance. Microsoft didn’t change anything in there between Windows 7 and 10 so aside from a couple defects I want to close it’s pretty close to being “done”.

The only thing with it is I had to pull EAP support until I can find someone using it to explain the use case so I can build a better API rather than just exposing an IntPtr extension.

I’d be interested in your feedback about the design changes and the ability to await the connection.

**Comment by mogikanin** [comment]
OK, I tried it.
1. `RasDialer.DialStateChanged` never raise 'Disconnected' state for case when we disconnect our connected connection. (i.e. after `RasConnection.HangUp()`)
2. If we specify incorrect username, then `RasDialer.DialAsync()` throws `RasException` with `NativeErrorCode= 691`. That's correct. But if we specify incorrect password, then occurs generic exception:
```
System.ArgumentException: The error code must be a positive value.
Parameter name: errorCode
   at DotRas.Internal.Services.ErrorHandling.RasGetErrorStringService.GetErrorString(Int32 errorCode)
   at DotRas.Internal.Policies.DefaultExceptionPolicy.Create(Int32 error)
   at DotRas.Internal.Services.Dialing.DefaultRasDialCallbackHandler.GuardErrorCodeMustBeZero(Int32 errorCode)
   at DotRas.Internal.Services.Dialing.DefaultRasDialCallbackHandler.OnCallback(IntPtr dwCallbackId, Int32 dwSubEntry, IntPtr hRasConn, UInt32 message, RasConnectionState connectionState, Int32 dwError, Int32 dwExtendedError)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleRunner.Program.<ConnectAsync>d__8.MoveNext() 
```
3. Suggestion: maybe expose to public api async methods for `RasConnection`: `EnumerateConnectionsAsync()`, `GetStatisticsAsync()`, `GetStatusAsync()`, `HangUpAsync()`?
4. If we issue `RasConnection.GetStatus()/GetStatistics()` after connection was terminated the exception occurs. If it expected behavior better document it in xml doc.

**Comment by jeff-winn** [comment]
What was the error code? It seems this area might be specific to the implementation of the RAS server you're trying to connect to. The VPN server I'm using seems to just kill the connection and return a -2143157998 error.

**Comment by jeff-winn** [comment]
That's the same thing I was seeing over here when entering bad credentials, except I got the -2143157998 response for both bad username and bad password. Seems to be specific to the RAS server being used on what response is thrown.

**Comment by jeff-winn** [comment]
Upon further investigation, the error code -2143157998 appears to be defined in EapErrorHost.h as EAP_E_USER_NAME_PASSWORD_REJECTED.

**Comment by jeff-winn** [comment]
Check out the issues/14 branch, I setup a new policy for use within the RasDialCallback to be able to translate additional items like this for long term maintenance. It should throw an EapException now when issues occur within EAP during the authentication callbacks.

Let me know what you think. At least this would be easier to work with than "Unknown error" and having to assume it means that authentication failed due to the state it was in when the exception occurred.

PS: Microsoft doesn't seem to expose a Win32 API to access these error messages which was why the message was hard-coded for the time being.

**Comment by mogikanin** [comment]
1. I like the idea that EAP errors should be detected somehow, but not like a separate Exception type for it.
Maybe it's quite enough just a boolean `IsEapError` inside `RasException`? My thought is too many exception types right now and client code will be quite dirty to handle all of them.
2. Btw, you forgot to mention 2 more exception types in xml doc for `DialXXX()` methods: `ObjectDisposedException` (from `GuardMustNotBeDisposed()`) and `FileNotFoundException`/`RasEntryNotFoundException` (from `ValidateConfigurationPriorToDialAttempt()`).

**Comment by jeff-winn** [comment]
So the primary reason behind using a separate exception type was because of the nature of the relationship of EAP and RAS. The RAS exceptions are generated by the RAS subsystem within Windows, whereas the EAP exception would need to come from the EAP related error codes. Identifying both of them as the same kind of exception could cause an issue identifying where they sourced from later. Just be aware, they both use Win32Exception as a base exception since they are both thrown from a Win32 API call.

I'm not entirely sure how a separate exception would cause the client code to get uglier, unless you're implying the try/catch block surrounding the Dial/DialAsync call would have additional catch blocks in it to display something to the user. This would really depend on your exception handling strategy used within your application.

Thanks for the info regarding the missing documentation, I'll make sure it gets added.

**Comment by jeff-winn** [comment]
I had a thought the other day, one of the major things most everyone would care about is an authentication exception. Yes EAP and RAS are internally separate exceptions but they could easily be wrapped in something easier to work with.

There would still be the general purpose RAS exception but it would also allow the centralization of logic that determines what is an authentication error into the DotRas code to limit developers from having to know and understand all 700 possible

**Comment by jeff-winn** [comment]
I had a thought the other day, one of the major things most everyone would care about is an authentication exception. Yes EAP and RAS are internally separate exceptions but they could easily be wrapped in something easier to work with.

There would still be the general purpose RAS exception but it would also allow the centralization of logic that determines what is an authentication error into the DotRas code to limit developers from having to know and understand all 700 possible
