### ISSUE TITLE
What separate WIN7, WIN8 and WIN10 configurations are for?

### ISSUE THREAD

**Issue by kirillkovalenko** [winnster/DotRas#46]
Hello Jeff, 

I've started investigating the DotRas project today and cannot understand the build configuration separation for three different platforms. 

Conditional compilation symbols are defined but apparently not used anywhere in the code.

Could you please elaborate?

**Comment by jeff-winn** [comment]
@kirillkovalenko, 

Those conditions are pushed in during my build process to produce the different NuGet packages that are compiled... Windows 7, Windows 8, and Windows 10 respectively.

They aren't used in my code, but rather change the exposed surface area of the DotRas API based on which version of Windows that you're targeting for your application (which is dependent on the NuGet package you've installed). Unlike normal backwards compatibility support provided by most applications, the Windows RAS subsystem is forward-only compatible rather than backwards compatible. Meaning if you use the DotRas.for.Win7 NuGet package variant it'll work on Windows 7, Windows 8, and Windows 10. However, the future Windows 10 variant will only work on Windows 10 or later. This is due to the underlying structure sizes that are passed into the interop area of the code and internally within Windows.

I've thought about other ways of handling the feature support, but the expectation from developers which consume the API would likely expect backwards compatibility which simply isn't the case with the OS. This would likely cause them to use a Windows 10 API on Windows 7 and see a large number of Win32 exceptions being thrown and end up raising issues here that I can't fix. I haven't produced a new API yet, and I'm still contemplating ways to deal with this, but for now the conditional compilation symbols are in place.

Hope that helps!

**Comment by kirillkovalenko** [comment]
Thanks Jeff.
