### ISSUE TITLE
Version of DotRas

### ISSUE THREAD

**Issue by Rick021** [winnster/DotRas#47]
@jeff-winn
Hi jeff-winn ,when I use your component DotRas ，I found many version such as DotRas.Win10 ,DotRas.Win8 ......,does that means only  the special OS we can used on it?

**Comment by jeff-winn** [comment]
It's to identify the minimum version of Windows required for it to work.

Win7 requires Windows 7 or higher.
Win8 requires Windows 8 or higher.

There isn't a Windows 10 official release yet, however the version hosted on here is what I've been using to develop it.

Since it's using OS interop, Microsoft's policy is one of forward compatibility rather than backwards compatibility. Features they add in Windows 7 are currently compatible with all versions of Windows they release after that. However, features they add in Windows 10 would make that version of DotRas  unusable on Windows 7. That's why they're named the way they are, to ensure developers aren't attempting to use features on versions of Windows that aren't supported by the OS.

**Comment by Rick021** [comment]
thanks  a lot.
